// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5W05lfEti0b0lzODHSnV6qaI7PK2CVgA',
    appId: '1:443678985890:web:c4cc0046a6dba5494491fb',
    messagingSenderId: '443678985890',
    projectId: 'todo-app-6cd2a',
    authDomain: 'todo-app-6cd2a.firebaseapp.com',
    storageBucket: 'todo-app-6cd2a.appspot.com',
    measurementId: 'G-47X4ZJ4QTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7tSJKbIs_2g-HZjLhp1Lkeb3xnd3NMI',
    appId: '1:443678985890:android:5d16eb7025206ce14491fb',
    messagingSenderId: '443678985890',
    projectId: 'todo-app-6cd2a',
    storageBucket: 'todo-app-6cd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznfnF3Zosy8vSb_FTdPfAc-ZRGVaRptA',
    appId: '1:443678985890:ios:808275043c5ccf5a4491fb',
    messagingSenderId: '443678985890',
    projectId: 'todo-app-6cd2a',
    storageBucket: 'todo-app-6cd2a.appspot.com',
    iosClientId:
        '443678985890-faj7qehs6tjccqfhlff1qu9h2djarvlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDznfnF3Zosy8vSb_FTdPfAc-ZRGVaRptA',
    appId: '1:443678985890:ios:728b268dc145fbc84491fb',
    messagingSenderId: '443678985890',
    projectId: 'todo-app-6cd2a',
    storageBucket: 'todo-app-6cd2a.appspot.com',
    iosClientId:
        '443678985890-63jac2s8j40tt8et6c89csnlu3qiaers.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
